import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;

// Interface for report generation
interface Reportable {
    void generateReport();
}

// Abstract class for User
abstract class User {
    private String username;
    private String password;
    
    public User(String username, String password) {
        this.username = username;
        this.password = password;
    }
    
    public String getUsername() {
        return username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    protected String getPassword() {
        return password;
    }
    
    public abstract void displayRole();
    
    public boolean authenticate(String inputPassword) {
        return this.password.equals(inputPassword);
    }
}

// Admin class
class Admin extends User implements Reportable {
    private String adminId;
    
    public Admin(String username, String password, String adminId) {
        super(username, password);
        this.adminId = adminId;
    }
    
    public String getAdminId() {
        return adminId;
    }
    
    @Override
    public void displayRole() {
        System.out.println("Role: Administrator");
    }
    
    @Override
    public void generateReport() {
        System.out.println("Report generated by: " + getUsername());
    }
}

// Abstract Product class
abstract class Product {
    private String productId;
    private String name;
    private double price;
    private int stockQuantity;
    
    public Product(String productId, String name, double price, int stockQuantity) {
        this.productId = productId;
        this.name = name;
        this.price = price;
        this.stockQuantity = stockQuantity;
    }
    
    public String getProductId() { return productId; }
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    public double getPrice() { return price; }
    public void setPrice(double price) { this.price = price; }
    public int getStockQuantity() { return stockQuantity; }
    public void setStockQuantity(int stockQuantity) { this.stockQuantity = stockQuantity; }
    
    public abstract String getCategory();
}

// Tool class
class Tool extends Product {
    private String toolType;
    
    public Tool(String productId, String name, double price, int stockQuantity, String toolType) {
        super(productId, name, price, stockQuantity);
        this.toolType = toolType;
    }
    
    @Override
    public String getCategory() {
        return "Tools - " + toolType;
    }
}

// Equipment class
class Equipment extends Product {
    private String equipmentType;
    
    public Equipment(String productId, String name, double price, int stockQuantity, String equipmentType) {
        super(productId, name, price, stockQuantity);
        this.equipmentType = equipmentType;
    }
    
    @Override
    public String getCategory() {
        return "Equipment - " + equipmentType;
    }
}

// Inventory Manager
class InventoryManager {
    private ArrayList<Product> products;
    
    public InventoryManager() {
        products = new ArrayList<>();
    }
    
    public void addProduct(Product product) {
        products.add(product);
    }
    
    public ArrayList<Product> getAllProducts() {
        return products;
    }
    
    public boolean updateProduct(String id, String name, double price, int stock) {
        for (Product p : products) {
            if (p.getProductId().equals(id)) {
                p.setName(name);
                p.setPrice(price);
                p.setStockQuantity(stock);
                return true;
            }
        }
        return false;
    }
    
    public boolean deleteProduct(String id) {
        return products.removeIf(p -> p.getProductId().equals(id));
    }
}

// Login Frame
class LoginFrame extends JFrame {
    private JTextField usernameField;
    private JPasswordField passwordField;
    private Admin admin;
    
    public LoginFrame() {
        admin = new Admin("admin", "admin123", "ADM001");
        
        setTitle("Lourdes Mini Hardware - Admin Login");
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);
        
        // Main panel with gradient-like background
        JPanel mainPanel = new JPanel();
        mainPanel.setLayout(null);
        mainPanel.setBackground(new Color(20, 20, 20));
        
        // Title label
        JLabel titleLabel = new JLabel("ADMIN LOGIN");
        titleLabel.setFont(new Font("Arial", Font.BOLD, 24));
        titleLabel.setForeground(new Color(255, 193, 7));
        titleLabel.setBounds(120, 30, 200, 30);
        mainPanel.add(titleLabel);
        
        // Username label and field
        JLabel userLabel = new JLabel("Username:");
        userLabel.setForeground(new Color(255, 193, 7));
        userLabel.setFont(new Font("Arial", Font.PLAIN, 14));
        userLabel.setBounds(50, 90, 100, 25);
        mainPanel.add(userLabel);
        
        usernameField = new JTextField();
        usernameField.setBounds(50, 115, 300, 30);
        usernameField.setFont(new Font("Arial", Font.PLAIN, 14));
        mainPanel.add(usernameField);
        
        // Password label and field
        JLabel passLabel = new JLabel("Password:");
        passLabel.setForeground(new Color(255, 193, 7));
        passLabel.setFont(new Font("Arial", Font.PLAIN, 14));
        passLabel.setBounds(50, 155, 100, 25);
        mainPanel.add(passLabel);
        
        passwordField = new JPasswordField();
        passwordField.setBounds(50, 180, 300, 30);
        passwordField.setFont(new Font("Arial", Font.PLAIN, 14));
        mainPanel.add(passwordField);
        
        // Login button
        JButton loginBtn = new JButton("LOGIN");
        loginBtn.setBounds(50, 225, 300, 35);
        loginBtn.setBackground(new Color(255, 193, 7));
        loginBtn.setForeground(Color.BLACK);
        loginBtn.setFont(new Font("Arial", Font.BOLD, 14));
        loginBtn.setFocusPainted(false);
        loginBtn.setBorderPainted(false);
        loginBtn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        loginBtn.addActionListener(e -> handleLogin());
        mainPanel.add(loginBtn);
        
        // Enter key to login
        passwordField.addActionListener(e -> handleLogin());
        
        add(mainPanel);
        setVisible(true);
    }
    
    private void handleLogin() {
        String username = usernameField.getText();
        String password = new String(passwordField.getPassword());
        
        if (username.equals(admin.getUsername()) && admin.authenticate(password)) {
            JOptionPane.showMessageDialog(this, "Login Successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
            dispose();
            new DashboardFrame(admin);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid username or password!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}

// Dashboard Frame
class DashboardFrame extends JFrame {
    private Admin admin;
    private InventoryManager inventory;
    private JTable productTable;
    private DefaultTableModel tableModel;
    
    public DashboardFrame(Admin admin) {
        this.admin = admin;
        this.inventory = new InventoryManager();
        
        // Add sample products
        inventory.addProduct(new Tool("T001", "Claw Hammer", 350.00, 25, "Hand Tool"));
        inventory.addProduct(new Equipment("E001", "Electric Drill", 2500.00, 10, "Power Tool"));
        inventory.addProduct(new Tool("T002", "Adjustable Wrench", 450.00, 15, "Hand Tool"));
        
        setTitle("Lourdes Mini Hardware - Dashboard");
        setSize(1000, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        
        // Main panel
        JPanel mainPanel = new JPanel(new BorderLayout());
        mainPanel.setBackground(Color.WHITE);
        
        // Header panel
        JPanel headerPanel = new JPanel();
        headerPanel.setBackground(new Color(20, 20, 20));
        headerPanel.setPreferredSize(new Dimension(1000, 80));
        headerPanel.setLayout(null);
        
        JLabel titleLabel = new JLabel("LOURDES MINI HARDWARE");
        titleLabel.setFont(new Font("Arial", Font.BOLD, 26));
        titleLabel.setForeground(new Color(255, 193, 7));
        titleLabel.setBounds(30, 15, 400, 30);
        headerPanel.add(titleLabel);
        
        JLabel adminLabel = new JLabel("Admin: " + admin.getUsername());
        adminLabel.setFont(new Font("Arial", Font.PLAIN, 14));
        adminLabel.setForeground(new Color(255, 193, 7));
        adminLabel.setBounds(30, 45, 300, 20);
        headerPanel.add(adminLabel);
        
        JButton logoutBtn = new JButton("Logout");
        logoutBtn.setBounds(880, 25, 90, 30);
        logoutBtn.setBackground(new Color(200, 50, 50));
        logoutBtn.setForeground(Color.WHITE);
        logoutBtn.setFocusPainted(false);
        logoutBtn.setBorderPainted(false);
        logoutBtn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        logoutBtn.addActionListener(e -> {
            dispose();
            new LoginFrame();
        });
        headerPanel.add(logoutBtn);
        
        // Control panel
        JPanel controlPanel = new JPanel();
        controlPanel.setBackground(new Color(40, 40, 40));
        controlPanel.setPreferredSize(new Dimension(1000, 70));
        
        JButton addBtn = createStyledButton("Add Product", new Color(255, 193, 7));
        addBtn.addActionListener(e -> showAddProductDialog());
        
        JButton updateBtn = createStyledButton("Update Product", new Color(255, 193, 7));
        updateBtn.addActionListener(e -> showUpdateProductDialog());
        
        JButton deleteBtn = createStyledButton("Delete Product", new Color(200, 50, 50));
        deleteBtn.addActionListener(e -> deleteSelectedProduct());
        
        JButton reportBtn = createStyledButton("Generate Report", new Color(255, 193, 7));
        reportBtn.addActionListener(e -> generateSalesReport());
        
        controlPanel.add(addBtn);
        controlPanel.add(updateBtn);
        controlPanel.add(deleteBtn);
        controlPanel.add(reportBtn);
        
        // Table panel
        String[] columnNames = {"Product ID", "Name", "Category", "Price (₱)", "Stock", "Status"};
        tableModel = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        productTable = new JTable(tableModel);
        productTable.setRowHeight(30);
        productTable.setFont(new Font("Arial", Font.PLAIN, 13));
        productTable.getTableHeader().setFont(new Font("Arial", Font.BOLD, 13));
        productTable.getTableHeader().setBackground(new Color(20, 20, 20));
        productTable.getTableHeader().setForeground(new Color(255, 193, 7));
        productTable.setSelectionBackground(new Color(255, 193, 7));
        
        JScrollPane scrollPane = new JScrollPane(productTable);
        
        refreshTable();
        
        mainPanel.add(headerPanel, BorderLayout.NORTH);
        mainPanel.add(controlPanel, BorderLayout.CENTER);
        mainPanel.add(scrollPane, BorderLayout.SOUTH);
        
        add(mainPanel);
        setVisible(true);
    }
    
    private JButton createStyledButton(String text, Color bgColor) {
        JButton btn = new JButton(text);
        btn.setPreferredSize(new Dimension(150, 40));
        btn.setBackground(bgColor);
        // Yellow buttons get black text, red buttons get white text
        if (bgColor.equals(new Color(255, 193, 7))) {
            btn.setForeground(Color.BLACK);
        } else {
            btn.setForeground(Color.WHITE);
        }
        btn.setFont(new Font("Arial", Font.BOLD, 12));
        btn.setFocusPainted(false);
        btn.setBorderPainted(false);
        btn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        return btn;
    }
    
    private void refreshTable() {
        tableModel.setRowCount(0);
        for (Product p : inventory.getAllProducts()) {
            String status = p.getStockQuantity() > 0 ? "Available" : "Out of Stock";
            tableModel.addRow(new Object[]{
                p.getProductId(),
                p.getName(),
                p.getCategory(),
                String.format("%.2f", p.getPrice()),
                p.getStockQuantity(),
                status
            });
        }
    }
    
    private void showAddProductDialog() {
        JDialog dialog = new JDialog(this, "Add New Product", true);
        dialog.setSize(400, 350);
        dialog.setLocationRelativeTo(this);
        dialog.setLayout(null);
        
        JLabel idLabel = new JLabel("Product ID:");
        idLabel.setBounds(30, 20, 100, 25);
        JTextField idField = new JTextField();
        idField.setBounds(150, 20, 200, 25);
        
        JLabel nameLabel = new JLabel("Name:");
        nameLabel.setBounds(30, 60, 100, 25);
        JTextField nameField = new JTextField();
        nameField.setBounds(150, 60, 200, 25);
        
        JLabel priceLabel = new JLabel("Price:");
        priceLabel.setBounds(30, 100, 100, 25);
        JTextField priceField = new JTextField();
        priceField.setBounds(150, 100, 200, 25);
        
        JLabel stockLabel = new JLabel("Stock:");
        stockLabel.setBounds(30, 140, 100, 25);
        JTextField stockField = new JTextField();
        stockField.setBounds(150, 140, 200, 25);
        
        JLabel typeLabel = new JLabel("Type:");
        typeLabel.setBounds(30, 180, 100, 25);
        String[] types = {"Tool", "Equipment"};
        JComboBox<String> typeCombo = new JComboBox<>(types);
        typeCombo.setBounds(150, 180, 200, 25);
        
        JLabel categoryLabel = new JLabel("Category:");
        categoryLabel.setBounds(30, 220, 100, 25);
        JTextField categoryField = new JTextField();
        categoryField.setBounds(150, 220, 200, 25);
        
        JButton addBtn = new JButton("Add Product");
        addBtn.setBounds(150, 270, 200, 35);
        addBtn.setBackground(new Color(255, 193, 7));
        addBtn.setForeground(Color.BLACK);
        addBtn.setFocusPainted(false);
        
        addBtn.addActionListener(e -> {
            try {
                String id = idField.getText();
                String name = nameField.getText();
                double price = Double.parseDouble(priceField.getText());
                int stock = Integer.parseInt(stockField.getText());
                String type = (String) typeCombo.getSelectedItem();
                String category = categoryField.getText();
                
                Product product;
                if (type.equals("Tool")) {
                    product = new Tool(id, name, price, stock, category);
                } else {
                    product = new Equipment(id, name, price, stock, category);
                }
                
                inventory.addProduct(product);
                refreshTable();
                JOptionPane.showMessageDialog(dialog, "Product added successfully!");
                dialog.dispose();
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(dialog, "Invalid price or stock value!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        });
        
        dialog.add(idLabel);
        dialog.add(idField);
        dialog.add(nameLabel);
        dialog.add(nameField);
        dialog.add(priceLabel);
        dialog.add(priceField);
        dialog.add(stockLabel);
        dialog.add(stockField);
        dialog.add(typeLabel);
        dialog.add(typeCombo);
        dialog.add(categoryLabel);
        dialog.add(categoryField);
        dialog.add(addBtn);
        
        dialog.setVisible(true);
    }
    
    private void showUpdateProductDialog() {
        int selectedRow = productTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a product to update!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String productId = (String) tableModel.getValueAt(selectedRow, 0);
        String currentName = (String) tableModel.getValueAt(selectedRow, 1);
        String currentPrice = (String) tableModel.getValueAt(selectedRow, 3);
        int currentStock = (int) tableModel.getValueAt(selectedRow, 4);
        
        JDialog dialog = new JDialog(this, "Update Product", true);
        dialog.setSize(400, 280);
        dialog.setLocationRelativeTo(this);
        dialog.setLayout(null);
        
        JLabel nameLabel = new JLabel("Name:");
        nameLabel.setBounds(30, 20, 100, 25);
        JTextField nameField = new JTextField(currentName);
        nameField.setBounds(150, 20, 200, 25);
        
        JLabel priceLabel = new JLabel("Price:");
        priceLabel.setBounds(30, 60, 100, 25);
        JTextField priceField = new JTextField(currentPrice);
        priceField.setBounds(150, 60, 200, 25);
        
        JLabel stockLabel = new JLabel("Stock:");
        stockLabel.setBounds(30, 100, 100, 25);
        JTextField stockField = new JTextField(String.valueOf(currentStock));
        stockField.setBounds(150, 100, 200, 25);
        
        JButton updateBtn = new JButton("Update Product");
        updateBtn.setBounds(150, 180, 200, 35);
        updateBtn.setBackground(new Color(255, 193, 7));
        updateBtn.setForeground(Color.BLACK);
        updateBtn.setFocusPainted(false);
        
        updateBtn.addActionListener(e -> {
            try {
                String name = nameField.getText();
                double price = Double.parseDouble(priceField.getText());
                int stock = Integer.parseInt(stockField.getText());
                
                if (inventory.updateProduct(productId, name, price, stock)) {
                    refreshTable();
                    JOptionPane.showMessageDialog(dialog, "Product updated successfully!");
                    dialog.dispose();
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(dialog, "Invalid price or stock value!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        });
        
        dialog.add(nameLabel);
        dialog.add(nameField);
        dialog.add(priceLabel);
        dialog.add(priceField);
        dialog.add(stockLabel);
        dialog.add(stockField);
        dialog.add(updateBtn);
        
        dialog.setVisible(true);
    }
    
    private void deleteSelectedProduct() {
        int selectedRow = productTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a product to delete!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String productId = (String) tableModel.getValueAt(selectedRow, 0);
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this product?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            if (inventory.deleteProduct(productId)) {
                refreshTable();
                JOptionPane.showMessageDialog(this, "Product deleted successfully!");
            }
        }
    }
    
    private void generateSalesReport() {
        admin.generateReport();
        
        // Create custom dialog
        JDialog reportDialog = new JDialog(this, "Sales Report", true);
        reportDialog.setSize(500, 600);
        reportDialog.setLocationRelativeTo(this);
        reportDialog.setLayout(new BorderLayout());
        
        // Header panel with black background
        JPanel headerPanel = new JPanel();
        headerPanel.setBackground(new Color(20, 20, 20));
        headerPanel.setPreferredSize(new Dimension(500, 80));
        headerPanel.setLayout(new BorderLayout());
        
        JLabel titleLabel = new JLabel("SALES REPORT", JLabel.CENTER);
        titleLabel.setFont(new Font("Arial", Font.BOLD, 24));
        titleLabel.setForeground(new Color(255, 193, 7));
        headerPanel.add(titleLabel, BorderLayout.CENTER);
        
        // Content panel
        JPanel contentPanel = new JPanel();
        contentPanel.setBackground(Color.WHITE);
        contentPanel.setLayout(new BoxLayout(contentPanel, BoxLayout.Y_AXIS));
        contentPanel.setBorder(BorderFactory.createEmptyBorder(20, 30, 20, 30));
        
        // Generate report data
        int lowStock = 0;
        double totalValue = 0;
        for (Product p : inventory.getAllProducts()) {
            if (p.getStockQuantity() < 10) lowStock++;
            totalValue += p.getPrice() * p.getStockQuantity();
        }
        
        // Add report information
        addReportLine(contentPanel, "Generated by:", admin.getUsername());
        addReportLine(contentPanel, "Date:", java.time.LocalDate.now().toString());
        
        contentPanel.add(Box.createVerticalStrut(20));
        
        JLabel summaryLabel = new JLabel("INVENTORY SUMMARY");
        summaryLabel.setFont(new Font("Arial", Font.BOLD, 16));
        summaryLabel.setForeground(new Color(20, 20, 20));
        summaryLabel.setAlignmentX(Component.LEFT_ALIGNMENT);
        contentPanel.add(summaryLabel);
        
        contentPanel.add(Box.createVerticalStrut(15));
        
        addReportLine(contentPanel, "Total Items in Inventory:", String.valueOf(inventory.getAllProducts().size()));
        addReportLine(contentPanel, "Low Stock Items (< 10):", String.valueOf(lowStock));
        addReportLine(contentPanel, "Total Inventory Value:", "₱" + String.format("%.2f", totalValue));
        
        contentPanel.add(Box.createVerticalStrut(20));
        
        // Products list
        JLabel productsLabel = new JLabel("PRODUCT DETAILS");
        productsLabel.setFont(new Font("Arial", Font.BOLD, 16));
        productsLabel.setForeground(new Color(20, 20, 20));
        productsLabel.setAlignmentX(Component.LEFT_ALIGNMENT);
        contentPanel.add(productsLabel);
        
        contentPanel.add(Box.createVerticalStrut(10));
        
        for (Product p : inventory.getAllProducts()) {
            JPanel productPanel = new JPanel();
            productPanel.setLayout(new BoxLayout(productPanel, BoxLayout.Y_AXIS));
            productPanel.setBackground(new Color(245, 245, 245));
            productPanel.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(200, 200, 200)),
                BorderFactory.createEmptyBorder(8, 10, 8, 10)
            ));
            productPanel.setAlignmentX(Component.LEFT_ALIGNMENT);
            
            JLabel nameLabel = new JLabel(p.getName() + " (" + p.getProductId() + ")");
            nameLabel.setFont(new Font("Arial", Font.BOLD, 12));
            productPanel.add(nameLabel);
            
            JLabel detailsLabel = new JLabel("₱" + String.format("%.2f", p.getPrice()) + " | Stock: " + p.getStockQuantity() + " | " + p.getCategory());
            detailsLabel.setFont(new Font("Arial", Font.PLAIN, 11));
            detailsLabel.setForeground(new Color(80, 80, 80));
            productPanel.add(detailsLabel);
            
            contentPanel.add(productPanel);
            contentPanel.add(Box.createVerticalStrut(5));
        }
        
        JScrollPane scrollPane = new JScrollPane(contentPanel);
        scrollPane.setBorder(null);
        
        // Button panel
        JPanel buttonPanel = new JPanel();
        buttonPanel.setBackground(new Color(40, 40, 40));
        buttonPanel.setPreferredSize(new Dimension(500, 60));
        
        JButton closeBtn = new JButton("Close");
        closeBtn.setPreferredSize(new Dimension(120, 35));
        closeBtn.setBackground(new Color(255, 193, 7));
        closeBtn.setForeground(Color.BLACK);
        closeBtn.setFont(new Font("Arial", Font.BOLD, 13));
        closeBtn.setFocusPainted(false);
        closeBtn.setBorderPainted(false);
        closeBtn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        closeBtn.addActionListener(e -> reportDialog.dispose());
        
        buttonPanel.add(closeBtn);
        
        reportDialog.add(headerPanel, BorderLayout.NORTH);
        reportDialog.add(scrollPane, BorderLayout.CENTER);
        reportDialog.add(buttonPanel, BorderLayout.SOUTH);
        
        reportDialog.setVisible(true);
    }
    
    private void addReportLine(JPanel panel, String label, String value) {
        JPanel linePanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 0, 5));
        linePanel.setBackground(Color.WHITE);
        linePanel.setAlignmentX(Component.LEFT_ALIGNMENT);
        
        JLabel labelText = new JLabel(label + " ");
        labelText.setFont(new Font("Arial", Font.BOLD, 13));
        labelText.setForeground(new Color(60, 60, 60));
        
        JLabel valueText = new JLabel(value);
        valueText.setFont(new Font("Arial", Font.PLAIN, 13));
        valueText.setForeground(new Color(20, 20, 20));
        
        linePanel.add(labelText);
        linePanel.add(valueText);
        panel.add(linePanel);
    }
}

// Main class
public class HardwareCatalogSystem {
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new LoginFrame());
    }
}